title: Streamdata Gallery
url: capital-one-devexchange.api.streamdata.gallery
tag: Capital One DevExchange
markdown: kramdown
exclude: [".rvmrc", ".rbenv-version", "README.md", "Rakefile", "changelog.md", ".DS_Store"]
github_user: streamdata-gallery-organizations
github_repo: capital-one-devexchange
github_branch: master
collections:
  listings:
    output: true
    permalink: /listings/:path/
defaults:
  - scope:
      type: listings
    values:
      layout: listings
